version: '3.8'
services:
  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - strapi

  strapi:
    image: strapi/strapi
    container_name: strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./strapi:/srv/app
    ports:
      - 1337:1337
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: strapi-mongodb
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: